#!/bin/sh

cd `dirname $0`/..

FILES="graphs.css graphs.html"
X_FILES="data/sc-rsi-crowdfund-collect.pl"
DIRS="ajax/ bin/ classes/ data/ js/ misc/"

chmod og+r ${FILES}
chmod u+x ${X_FILES}
chmod og+X ${DIRS}
find ${DIRS} -type f -print0 | xargs -0 chmod og+r


